# Generated by Django 5.0.1 on 2024-01-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('subscriber', 'subscriber')], default='subscriber', max_length=10, null=True),
        ),
    ]
