# Generated by Django 5.0.1 on 2024-01-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_postrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrating',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
