# Generated by Django 5.0.1 on 2024-01-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_postrating_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
